namespace FluidScript.Core.Catalogs.Valves;

/// <summary>The R5 preferred-number series, which is what valve Kvs values step on.</summary>
/// <remarks>
/// <para>
/// <strong>These rows are generated, not transcribed, and <c>D-84</c> is why that changes their
/// provenance.</strong> R5 is the Renard series <c>10^(n/5)</c>, rounded as ISO 3 rounds it: 1.00,
/// 1.60, 2.50, 4.00, 6.30 and the same pattern in every decade. `27`'s two-source rule exists to catch
/// a transcription error in a measurement, and there is no measurement here — so the row's defence is
/// the formula, stated in <see cref="Catalogs.Provenance.Computed"/>, and a test that regenerates every
/// literal below from it. A typo in this table is a build failure rather than a sizing error.
/// </para>
/// <para>
/// <strong>It is a generic series and says so.</strong> A real valve has a Kvs its manufacturer
/// publishes, and the good ones land on R5 because that is what the series is for; the bad ones do
/// not. Sizing against R5 gives an answer of the right shape and the right step, and a script that
/// needs a specific product states its <c>kv</c> outright. A sourced manufacturer series can be added
/// beside this one without changing the rule, which is why the rule selects through
/// <see cref="ICatalog{TSpec}"/> rather than through this class.
/// </para>
/// <para>
/// <strong>The R5 step is 1.6× in Kv and therefore 2.56× in pressure drop</strong>, which is coarse.
/// That coarseness is the whole of <c>C-49</c>: rounding a *balancing* valve to it destroys the
/// proportional balance the same document requires, because a real balancing valve has a discrete body
/// and a <em>continuous</em> preset. This catalogue is for control valves, where rounding down is
/// correct and raises authority.
/// </para>
/// </remarks>
public static class ValveKvR5
{
    /// <summary>The catalogue id a script pins.</summary>
    public const string Id = "valve_kv_r5";

    /// <summary>The rule every row is generated by, and the attestation `D-84` puts in its place.</summary>
    public const string GeneratingRule = "R5 Renard series: 10^(n/5), rounded as ISO 3 rounds it";

    /// <summary>The series name a basis string prints.</summary>
    public const string SeriesName = "R5 preferred numbers";

    /// <summary>Every R5 Kvs value this catalogue offers, ascending.</summary>
    /// <remarks>
    /// Written out rather than generated at run time so a reader can see the table, and regenerated by
    /// a test so the literals cannot drift from the rule. The span is DN10 trim to roughly DN200, which
    /// is the range a hydronic script reaches; the registry binds `kv` well past both ends.
    /// </remarks>
    public static readonly double[] Values =
    [
        0.10, 0.16, 0.25, 0.40, 0.63,
        1.0, 1.6, 2.5, 4.0, 6.3,
        10, 16, 25, 40, 63,
        100, 160, 250, 400, 630,
    ];

    /// <summary>The catalogue, ascending by Kvs.</summary>
    public static ICatalog<ValveSpec> Instance { get; } = new Catalog<ValveSpec>(
        Id,
        "1",
        "ISO 3",
        Values.Select(static kvs => new CatalogEntry<ValveSpec>
        {
            Designation = $"Kv {kvs:0.##}",
            Spec = new ValveSpec { Kvs = kvs, Series = SeriesName },
            Provenance = new Provenance
            {
                Standard = "ISO 3",
                Computed = GeneratingRule,
                Verified = true,
            },
        }),
        ValveSpec.Fault,
        static spec => spec.Kvs);
}
