using System.Collections.Immutable;

namespace FluidScript.Core.Catalogs;

/// <summary>One public document a catalogue row was read from.</summary>
/// <param name="Publisher">Who published it — a manufacturer, not a standards body's paywall.</param>
/// <param name="Url">The public URL it was read from.</param>
/// <param name="Retrieved">The date it was read, because a manufacturer's catalogue is revised.</param>
public sealed record SourceReference(string Publisher, string Url, DateOnly Retrieved);

/// <summary>Where a catalogue value came from, and whether a person checked it.</summary>
/// <remarks>
/// <para>
/// <strong>Two sources, and a human.</strong> A single manufacturer's typo becomes a silent sizing
/// error affecting every circuit that lands on that diameter: a wrong bore propagates into velocity,
/// Reynolds number, friction factor and pump head, and the result looks entirely reasonable at every
/// step. Two independent sources agreeing is the cheapest check that catches it.
/// </para>
/// <para>
/// <see cref="Standard"/> cites the standard by <em>number only</em>. The dimensions themselves are
/// facts about physical objects and are not copyrightable; a standard's table layout, selection,
/// arrangement and notes are, and none of them appears in this repository.
/// </para>
/// </remarks>
public sealed record Provenance
{
    /// <summary>The standard this row conforms to, cited by number.</summary>
    /// <value><c>"EN 10255"</c>, or <see langword="null"/> for a manufacturer-specific value.</value>
    public string? Standard { get; init; }

    /// <summary>The public sources consulted.</summary>
    /// <value>At least two for a verified row; may be empty while a row awaits sourcing.</value>
    public ImmutableArray<SourceReference> Sources { get; init; } = [];

    /// <summary>Whether a person checked this row against the sources above.</summary>
    /// <remarks>
    /// An attestation, not a computation, and nothing may set it from the data. A row that reaches a
    /// user unverified is a design defended by nobody.
    /// </remarks>
    public required bool Verified { get; init; }

    /// <summary>The closed-form rule this row is generated by, when it is generated rather than read.</summary>
    /// <value>
    /// <c>"R5 Renard series, 10^(n/5) rounded as ISO 3 rounds it"</c>, or <see langword="null"/> for a
    /// row that states a fact about a physical object.
    /// </value>
    /// <remarks>
    /// <para>
    /// <strong>Setting this on a measured row is a lie in a field named for the truth</strong> (<c>D-84</c>).
    /// A bore, a wall thickness and a mass per metre are measurements; no formula generates them, and a
    /// string claiming one would buy a row past the check that exists to catch exactly that row.
    /// </para>
    /// <para>
    /// What it is for is a series whose values <em>are</em> an expression. Two sources on such a table
    /// attest that two people copied the same arithmetic correctly, which is weaker than the arithmetic;
    /// the real attestation is a test that regenerates every row from the rule named here.
    /// </para>
    /// </remarks>
    public string? Computed { get; init; }

    /// <summary>Whether this row may be used to size anything.</summary>
    /// <value>
    /// <see langword="true"/> when a person verified it <em>and</em> it is defended: by two or more
    /// independent sources for a measured row, or by <see cref="Computed"/> for a generated one.
    /// <see cref="Verified"/> is required either way -- the formula says the values are right, and only
    /// a person can say the series is the one that was meant.
    /// </value>
    public bool IsUsable => Verified && (Sources.Length >= 2 || Computed is not null);
}

/// <summary>One selectable size from a catalogue.</summary>
/// <typeparam name="TSpec">The dimensional record this catalogue holds.</typeparam>
public sealed record CatalogEntry<TSpec>
{
    /// <summary>The designation as an engineer would write it.</summary>
    /// <value><c>"DN25"</c>, <c>"Kv 1.6"</c>.</value>
    public required string Designation { get; init; }

    /// <summary>The dimensional data.</summary>
    public required TSpec Spec { get; init; }

    /// <summary>Where this row came from and when.</summary>
    /// <remarks>
    /// Never absent. A row without provenance cannot be defended when a user asks why their pipe is
    /// 27.3 mm, and cannot be audited when a value turns out to be wrong.
    /// </remarks>
    public required Provenance Provenance { get; init; }
}
